version: '3.8'

services:
  db:
    image: postgres:16
    container_name: pgcomunica
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: comunicaMais
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  api:
    build: .
    container_name: comunica-api
    restart: always
    command: npm start
    # Expondo a API na porta 3331 do servidor.
    # O Nginx principal vai se conectar a esta porta.
    # O 3000 é a porta interna da sua aplicação Node.js.
    ports:
      - "3331:3000"
    environment:
      DB_USER: local
      DB_PASSWORD: 12345
      DB_NAME: comunicaMais
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge

