# Arquivo: docker-compose.yml

version: '3.8'
services:
  db:
    image: postgres:16
    container_name: pgcomunica
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: comunicaMais
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  api:
    build: .
    container_name: comunica-api
    command: npm start
    environment:
      DB_USER: local
      DB_PASSWORD: 12345
      DB_NAME: comunicaMais
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - api
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge